---- Base app schema

-- House
CREATE TABLE "house"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    house_name  varchar(64) NOT NULL UNIQUE
);


-- Room
CREATE TABLE "room"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    house_id    BIGINT NOT NULL,
    room_name   varchar(64) NOT NULL
);

ALTER TABLE "room" ADD CONSTRAINT "UQ_fd8103546d27f304988c650cb60"
    UNIQUE ("house_id", "room_name");

ALTER TABLE "room"
    ADD CONSTRAINT "FK_cc57403bd3c8ee20e31c20292cb" FOREIGN KEY ("house_id")
        REFERENCES "house" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;


-- Device
CREATE TABLE "device"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    room_id     BIGINT NOT NULL,
    device_name varchar(64) NOT NULL,
    device_type varchar(64) NOT NULL
);

ALTER TABLE "device" ADD CONSTRAINT "UQ_fd8103546d27f304988c6501234"
    UNIQUE ("room_id", "device_name");

ALTER TABLE "device"
    ADD CONSTRAINT "FK_cc57403bd3c8ee20e31c2024567" FOREIGN KEY ("room_id")
        REFERENCES "room" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;