[package]
name = "ffi_socket_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
tcp-socket.workspace = true
tokio = { version = "1", features = ["full"]}
libloading = "0.8.6"

[lib]
crate-type = ["cdylib"]
